--ATRAVÉS DO LAG É POSSÍVEL CRIAR UMA RELAÇÃO ENTRE UMA LINHA E A OU AS LINHAS ACIMA A MESMA [LAG(COLUNA, QUANTIDADE LINHAS ACIMA)]
WITH CTE AS (
              SELECT 
                    EXTRACT(YEAR FROM PADATNAS) AS ANO,
                    COUNT(*) AS QNT_NASCIDOS
                FROM SAUDEWEB.TBPACIEN
                GROUP BY EXTRACT(YEAR FROM PADATNAS)
                ORDER BY EXTRACT(YEAR FROM PADATNAS)
), CTE2 AS (
		SELECT 
		    ANO,
		    QNT_NASCIDOS,
		    LAG(ANO, 1) OVER (ORDER BY ANO) AS ANO_ANTERIOR,
		    LAG(QNT_NASCIDOS, 1) OVER (ORDER BY ANO) AS QNT_ANTERIOR
		FROM CTE
	)	
		SELECT 
			ANO,
			ANO_ANTERIOR,
			QNT_NASCIDOS - QNT_ANTERIOR AS DIF_ANO_ANTERIOR
	        FROM CTE2